#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARTIFACT_DIR="${RUNNER_TEMP:-$ROOT/.tmp}/vdn-release-validation"
BOOTSTRAP_REPAIR="$ROOT/supabase/migrations/20260722999999_release_validation_bootstrap_compatibility.sql"
mkdir -p "$ARTIFACT_DIR"
CURRENT_STAGE="bootstrap"

report_failure() {
  local line_number="${1:-unknown}"
  local exit_code="${2:-1}"
  trap - ERR
  printf '::error file=scripts/release-validation/run-disposable-validation.sh,line=%s,title=Disposable validation failed::stage=%s exit=%s\n' \
    "$line_number" "$CURRENT_STAGE" "$exit_code"

  find "$ARTIFACT_DIR" -type f -name '*.log' -printf '%T@ %p\n' 2>/dev/null \
    | sort -nr | head -n 3 | cut -d' ' -f2- \
    | while IFS= read -r failure_log; do
      sed -E \
        -e 's#(postgres(ql)?://[^:[:space:]]+:)[^@[:space:]]+@#\1[REDACTED]@#g' \
        -e 's#eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+#[REDACTED_JWT]#g' \
        -e 's#(sb_(secret|publishable)_[A-Za-z0-9_-]+)#[REDACTED_KEY]#g' \
        "$failure_log" \
        | grep -Ei 'error|failed|denied|invalid|duplicate|violates|does not exist|already exists|not found' \
        | tail -n 3 \
        | while IFS= read -r diagnostic; do
          printf '::error file=scripts/release-validation/run-disposable-validation.sh,line=%s,title=%s::%s\n' \
            "$line_number" "$(basename "$failure_log")" "$diagnostic"
        done
    done
  exit "$exit_code"
}
trap 'report_failure $LINENO $?' ERR

eval "$(supabase status -o env)"
export SUPABASE_URL="$API_URL"
export SUPABASE_PUBLISHABLE_KEY="$ANON_KEY"
export SUPABASE_SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY"
export DB_URL

case "$SUPABASE_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *) echo "Refusing non-local Supabase URL" >&2; exit 70 ;;
esac
case "$DB_URL" in
  postgresql://postgres:postgres@127.0.0.1:*/*|postgresql://postgres:postgres@localhost:*/*) ;;
  *) echo "Refusing non-local database URL" >&2; exit 71 ;;
esac

node "$ROOT/scripts/release-validation/analyze-migrations.mjs" \
  --write "$ARTIFACT_DIR/migration-inventory.json"

echo "scenario=A clean installation"
CURRENT_STAGE="scenario-a-clean-install"
start_a="$(date +%s)"
supabase db reset --no-seed >"$ARTIFACT_DIR/scenario-a-reset.log" 2>&1
psql "$DB_URL" -At -f "$ROOT/scripts/release-validation/v2-schema-check.sql" \
  >"$ARTIFACT_DIR/scenario-a-schema.json"
end_a="$(date +%s)"

printf 'test,status\n' >"$ARTIFACT_DIR/external-tests.csv"
external_failure_count=0

# Disposable-only control table. This distinguishes a local Realtime runtime
# failure from application-specific RLS/policy failures without changing the
# versioned product schema or any shared environment.
psql "$DB_URL" -v ON_ERROR_STOP=1 >"$ARTIFACT_DIR/realtime-probe-bootstrap.log" <<'SQL'
CREATE TABLE public.release_validation_realtime_probe (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL,
  marker text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.release_validation_realtime_probe ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.release_validation_realtime_probe TO authenticated;
GRANT ALL ON public.release_validation_realtime_probe TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.release_validation_realtime_probe_id_seq
  TO service_role;
CREATE POLICY "release validation owner reads probe"
  ON public.release_validation_realtime_probe
  FOR SELECT TO authenticated
  USING (owner_id = auth.uid());
ALTER PUBLICATION supabase_realtime
  ADD TABLE public.release_validation_realtime_probe;
SQL

for external_test in \
  tests/starter-bundle.test.ts \
  tests/messages-rls.test.ts \
  tests/moderation-rls.test.ts \
  tests/chat-e2e.test.ts \
  tests/realtime-infrastructure.test.ts \
  tests/realtime-messages.test.ts \
  tests/push-dispatch-atomic-rls.test.ts \
  tests/trusted-capabilities-rls.test.ts; do
  test_name="$(basename "$external_test")"
  if bun run test -- "$external_test" \
    >"$ARTIFACT_DIR/${test_name%.test.ts}.log" 2>&1; then
    printf '%s,passed\n' "$test_name" >>"$ARTIFACT_DIR/external-tests.csv"
  else
    printf '%s,failed\n' "$test_name" >>"$ARTIFACT_DIR/external-tests.csv"
    external_failure_count=$((external_failure_count + 1))
    failure_log="$ARTIFACT_DIR/${test_name%.test.ts}.log"
    if [[ "$test_name" == "realtime-messages.test.ts" ]]; then
      psql "$DB_URL" -At >"$ARTIFACT_DIR/realtime-database-diagnostic.log" <<'SQL'
SELECT 'published=' || EXISTS (
  SELECT 1
  FROM pg_publication_tables
  WHERE pubname = 'supabase_realtime'
    AND schemaname = 'public'
    AND tablename = 'messages'
);
SELECT 'replica_identity=' || relreplident
FROM pg_class
WHERE oid = 'public.messages'::regclass;
SELECT 'authenticated_select=' ||
  has_table_privilege('authenticated', 'public.messages', 'SELECT');
SELECT 'active_replication_slots=' || count(*)
FROM pg_replication_slots
WHERE active;
SQL
      while IFS= read -r diagnostic; do
        printf '::warning file=scripts/release-validation/run-disposable-validation.sh,line=%s,title=Realtime database diagnostic::%s\n' \
          "$LINENO" "$diagnostic"
      done <"$ARTIFACT_DIR/realtime-database-diagnostic.log"

      realtime_container_id="$(
        docker ps --filter 'name=supabase_realtime_' --format '{{.ID}}' | head -n 1
      )"
      if [[ -n "$realtime_container_id" ]]; then
        docker logs --tail 250 "$realtime_container_id" 2>&1 \
          | sed -E \
              -e 's#(postgres(ql)?://[^:[:space:]]+:)[^@[:space:]]+@#\1[REDACTED]@#g' \
              -e 's#eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+#[REDACTED_JWT]#g' \
              -e 's#(sb_(secret|publishable)_[A-Za-z0-9_-]+)#[REDACTED_KEY]#g' \
          >"$ARTIFACT_DIR/realtime-container.log"
        while IFS= read -r diagnostic; do
          printf '::warning file=scripts/release-validation/run-disposable-validation.sh,line=%s,title=Realtime container diagnostic::%s\n' \
            "$LINENO" "$diagnostic"
        done < <(
          grep -Ei 'error|failed|rls|replication|postgres.*change|subscription' \
            "$ARTIFACT_DIR/realtime-container.log" | tail -n 12
        )
      fi
    fi
    while IFS= read -r diagnostic; do
      printf '::error file=scripts/release-validation/run-disposable-validation.sh,line=%s,title=%s::%s\n' \
        "$LINENO" "$test_name" "$diagnostic"
    done < <(
      sed -E \
        -e 's#(postgres(ql)?://[^:[:space:]]+:)[^@[:space:]]+@#\1[REDACTED]@#g' \
        -e 's#eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+#[REDACTED_JWT]#g' \
        -e 's#(sb_(secret|publishable)_[A-Za-z0-9_-]+)#[REDACTED_KEY]#g' \
        "$failure_log" \
        | grep -Ei 'error|failed|denied|invalid|duplicate|violates|does not exist|already exists|not found' \
        | tail -n 3
    )
  fi
done

psql "$DB_URL" -v ON_ERROR_STOP=1 >"$ARTIFACT_DIR/realtime-probe-cleanup.log" <<'SQL'
ALTER PUBLICATION supabase_realtime
  DROP TABLE public.release_validation_realtime_probe;
DROP TABLE public.release_validation_realtime_probe;
SQL

echo "scenario=B representative upgrade"
CURRENT_STAGE="scenario-b-representative-upgrade"
start_b="$(date +%s)"
supabase db reset --version 20260622200000 --no-seed \
  >"$ARTIFACT_DIR/scenario-b-baseline.log" 2>&1
psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$BOOTSTRAP_REPAIR" \
  >"$ARTIFACT_DIR/scenario-b-bootstrap-repair.log" 2>&1
node "$ROOT/scripts/release-validation/seed-synthetic.mjs" \
  "$ARTIFACT_DIR/synthetic-seed.json"
psql "$DB_URL" -At -f "$ROOT/scripts/release-validation/integrity-snapshot.sql" \
  >"$ARTIFACT_DIR/scenario-b-before.json"

printf 'migration,status,duration_ms\n' >"$ARTIFACT_DIR/migration-execution.csv"
for migration in "$ROOT"/supabase/migrations/202607230000*_v2_*.sql; do
  name="$(basename "$migration")"
  started="$(date +%s%3N)"
  if psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$migration" \
    >"$ARTIFACT_DIR/${name%.sql}.log" 2>&1; then
    status="passed"
  else
    status="failed"
  fi
  finished="$(date +%s%3N)"
  printf '%s,%s,%s\n' "$name" "$status" "$((finished-started))" \
    >>"$ARTIFACT_DIR/migration-execution.csv"
  [[ "$status" == "passed" ]] || exit 72
done
psql "$DB_URL" -At -f "$ROOT/scripts/release-validation/integrity-snapshot.sql" \
  >"$ARTIFACT_DIR/scenario-b-after.json"
cmp "$ARTIFACT_DIR/scenario-b-before.json" "$ARTIFACT_DIR/scenario-b-after.json"
psql "$DB_URL" -At -f "$ROOT/scripts/release-validation/v2-schema-check.sql" \
  >"$ARTIFACT_DIR/scenario-b-schema.json"
end_b="$(date +%s)"

echo "scenario=C controlled intermediate failure"
CURRENT_STAGE="scenario-c-intermediate-failure"
supabase db reset --version 20260622200000 --no-seed \
  >"$ARTIFACT_DIR/scenario-c-baseline.log" 2>&1
psql "$DB_URL" -v ON_ERROR_STOP=1 \
  -f "$BOOTSTRAP_REPAIR" \
  -f "$ROOT/supabase/migrations/20260723000001_v2_trusted_reward_capabilities.sql" \
  -f "$ROOT/supabase/migrations/20260723000002_v2_atomic_push_dispatch.sql" \
  >"$ARTIFACT_DIR/scenario-c-prerequisites.log" 2>&1
trap - ERR
set +e
psql "$DB_URL" -v ON_ERROR_STOP=1 >"$ARTIFACT_DIR/scenario-c-forced-failure.log" 2>&1 <<SQL
BEGIN;
\i $ROOT/supabase/migrations/20260723000003_v2_photo_repair_audit.sql
SELECT 1 / 0;
COMMIT;
SQL
forced_exit=$?
set -e
trap 'report_failure $LINENO $?' ERR
[[ "$forced_exit" -ne 0 ]] || { echo "forced failure unexpectedly succeeded" >&2; exit 73; }
test "$(psql "$DB_URL" -Atc "SELECT to_regclass('public.photo_repair_audit') IS NULL")" = "t"
psql "$DB_URL" -v ON_ERROR_STOP=1 \
  -f "$ROOT/supabase/migrations/20260723000003_v2_photo_repair_audit.sql" \
  >"$ARTIFACT_DIR/scenario-c-recovery.log" 2>&1

echo "scenario=D controlled repetition"
CURRENT_STAGE="scenario-d-controlled-repeat"
psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$BOOTSTRAP_REPAIR" \
  >"$ARTIFACT_DIR/scenario-d-bootstrap-repair.log" 2>&1
for migration in "$ROOT"/supabase/migrations/202607230000*_v2_*.sql; do
  psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$migration" \
    >>"$ARTIFACT_DIR/scenario-d-complete.log" 2>&1
done
printf 'migration,status\n' >"$ARTIFACT_DIR/migration-repeat.csv"
for migration in "$ROOT"/supabase/migrations/202607230000*_v2_*.sql; do
  name="$(basename "$migration")"
  if psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$migration" \
    >>"$ARTIFACT_DIR/scenario-d-repeat.log" 2>&1; then
    printf '%s,repeatable\n' "$name" >>"$ARTIFACT_DIR/migration-repeat.csv"
  else
    printf '%s,not-repeatable\n' "$name" >>"$ARTIFACT_DIR/migration-repeat.csv"
  fi
done
not_repeatable_count="$(grep -c ',not-repeatable' "$ARTIFACT_DIR/migration-repeat.csv" || true)"

echo "backup and restore"
CURRENT_STAGE="backup-and-restore"
supabase db reset --version 20260622200000 --no-seed \
  >"$ARTIFACT_DIR/backup-baseline.log" 2>&1
psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$BOOTSTRAP_REPAIR" \
  >"$ARTIFACT_DIR/backup-bootstrap-repair.log" 2>&1
node "$ROOT/scripts/release-validation/seed-synthetic.mjs" \
  "$ARTIFACT_DIR/backup-seed.json"
for migration in "$ROOT"/supabase/migrations/202607230000*_v2_*.sql; do
  psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$migration" >/dev/null
done
psql "$DB_URL" -At -f "$ROOT/scripts/release-validation/integrity-snapshot.sql" \
  >"$ARTIFACT_DIR/backup-source.json"
DB_CONTAINER_ID="$(docker ps --filter 'name=supabase_db_' --format '{{.ID}}' | head -n 1)"
[[ -n "$DB_CONTAINER_ID" ]] || {
  echo "local Supabase database container not found" >"$ARTIFACT_DIR/pg-dump.log"
  exit 76
}
docker exec "$DB_CONTAINER_ID" \
  pg_dump --username postgres --dbname postgres --format=custom \
  >"$ARTIFACT_DIR/validated.backup" 2>"$ARTIFACT_DIR/pg-dump.log"
docker exec -i "$DB_CONTAINER_ID" pg_restore --list \
  <"$ARTIFACT_DIR/validated.backup" >"$ARTIFACT_DIR/backup-manifest.txt"

mapfile -t AUXILIARY_CONTAINERS < <(
  docker ps --filter 'name=supabase_' --format '{{.ID}}' | grep -v "^${DB_CONTAINER_ID}$"
)
if [[ "${#AUXILIARY_CONTAINERS[@]}" -gt 0 ]]; then
  docker stop "${AUXILIARY_CONTAINERS[@]}" >"$ARTIFACT_DIR/restore-services-stop.log"
fi
docker exec -i "$DB_CONTAINER_ID" \
  psql --username supabase_admin --dbname template1 -v ON_ERROR_STOP=1 \
  >"$ARTIFACT_DIR/restore-database-create.log" 2>&1 <<'SQL'
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'postgres' AND pid <> pg_backend_pid();
ALTER DATABASE postgres RENAME TO source_validation;
CREATE DATABASE postgres OWNER postgres;
SQL

RESTORE_DB_URL="$DB_URL"
if ! docker exec -i "$DB_CONTAINER_ID" \
  pg_restore --username supabase_admin --dbname postgres \
  --exit-on-error \
  <"$ARTIFACT_DIR/validated.backup" >"$ARTIFACT_DIR/restore.log" 2>&1; then
  while IFS= read -r diagnostic; do
    printf '::error file=scripts/release-validation/run-disposable-validation.sh,line=%s,title=Restore diagnostic::%s\n' \
      "$LINENO" "$diagnostic"
  done < <(
    sed -E \
      -e 's#(postgres(ql)?://[^:[:space:]]+:)[^@[:space:]]+@#\1[REDACTED]@#g' \
      -e 's#eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+#[REDACTED_JWT]#g' \
      "$ARTIFACT_DIR/restore.log" \
      | grep -Ei -B 2 -A 6 'error:|detail:|hint:' \
      | head -n 8
  )
  exit 77
fi
psql "$RESTORE_DB_URL" -At -f "$ROOT/scripts/release-validation/integrity-snapshot.sql" \
  >"$ARTIFACT_DIR/backup-restored.json"
cmp "$ARTIFACT_DIR/backup-source.json" "$ARTIFACT_DIR/backup-restored.json"
psql "$RESTORE_DB_URL" -At -f "$ROOT/scripts/release-validation/v2-schema-check.sql" \
  >"$ARTIFACT_DIR/restore-schema.json"
if [[ "${#AUXILIARY_CONTAINERS[@]}" -gt 0 ]]; then
  docker start "${AUXILIARY_CONTAINERS[@]}" >"$ARTIFACT_DIR/restore-services-start.log"
fi
auth_ready=false
for _attempt in $(seq 1 45); do
  if curl --fail --silent --show-error --connect-timeout 2 --max-time 3 \
    "$SUPABASE_URL/auth/v1/health" \
    >"$ARTIFACT_DIR/post-restore-auth-health.json" 2>"$ARTIFACT_DIR/post-restore-auth-health.log"; then
    auth_ready=true
    break
  fi
  sleep 2
done
[[ "$auth_ready" == "true" ]] || {
  echo "Auth did not become healthy within 90 seconds" >>"$ARTIFACT_DIR/post-restore-auth-health.log"
  exit 78
}
timeout 120s bun run test -- tests/starter-bundle.test.ts \
  >"$ARTIFACT_DIR/post-restore-smoke.log" 2>&1

sha256sum "$ARTIFACT_DIR/validated.backup" >"$ARTIFACT_DIR/backup.sha256"
rm -f "$ARTIFACT_DIR/validated.backup"
cat >"$ARTIFACT_DIR/run-summary.json" <<JSON
{
  "schemaVersion": 1,
  "environment": "ephemeral-github-actions-local-supabase",
  "productionAccessed": false,
  "historicalMigrations": 213,
  "preV2HistoricalMigrations": 196,
  "bootstrapCompatibilityMigrations": 1,
  "v2Migrations": 16,
  "scenarioASeconds": $((end_a-start_a)),
  "scenarioBSeconds": $((end_b-start_b)),
  "cleanInstall": "passed",
  "representativeUpgrade": "passed",
  "intermediateFailureRollback": "passed",
  "controlledRepeat": "completed",
  "notRepeatableMigrations": $not_repeatable_count,
  "externalTestFailures": $external_failure_count,
  "backupCreated": true,
  "backupRestoredToNewDatabase": true,
  "postRestoreIntegrity": "passed",
  "postRestoreAuthDataSmoke": "passed"
}
JSON
cat "$ARTIFACT_DIR/run-summary.json"
printf '::notice title=Disposable release validation summary::clean=passed upgrade=passed failureRollback=passed repeat=completed backupRestore=passed externalFailures=%s scenarioASeconds=%s scenarioBSeconds=%s notRepeatable=%s\n' \
  "$external_failure_count" "$((end_a-start_a))" "$((end_b-start_b))" "$not_repeatable_count"
if [[ "$external_failure_count" -gt 0 ]]; then
  printf '::error file=scripts/release-validation/run-disposable-validation.sh,line=%s,title=External Supabase suites failed::count=%s; see external-tests.csv and annotations\n' \
    "$LINENO" "$external_failure_count"
  exit 75
fi
