/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificacaoRouteImport } from './routes/verificacao'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as InteressesRouteImport } from './routes/interesses'
import { Route as DevocionalRouteImport } from './routes/devocional'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BloqueadosRouteImport } from './routes/bloqueados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuporteIndexRouteImport } from './routes/suporte/index'
import { Route as PretendentesIndexRouteImport } from './routes/pretendentes/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as ConversasIndexRouteImport } from './routes/conversas/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SuporteAjudaRouteImport } from './routes/suporte/ajuda'
import { Route as SuporteIdRouteImport } from './routes/suporte/$id'
import { Route as PretendentesIdRouteImport } from './routes/pretendentes/$id'
import { Route as OnboardingEtapa2RouteImport } from './routes/onboarding/etapa-2'
import { Route as OnboardingEtapa1RouteImport } from './routes/onboarding/etapa-1'
import { Route as ConversasMatchIdRouteImport } from './routes/conversas/$matchId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminVerificacoesRouteImport } from './routes/admin/verificacoes'

const VerificacaoRoute = VerificacaoRouteImport.update({
  id: '/verificacao',
  path: '/verificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const InteressesRoute = InteressesRouteImport.update({
  id: '/interesses',
  path: '/interesses',
  getParentRoute: () => rootRouteImport,
} as any)
const DevocionalRoute = DevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadosRoute = BloqueadosRouteImport.update({
  id: '/bloqueados',
  path: '/bloqueados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteIndexRoute = SuporteIndexRouteImport.update({
  id: '/suporte/',
  path: '/suporte/',
  getParentRoute: () => rootRouteImport,
} as any)
const PretendentesIndexRoute = PretendentesIndexRouteImport.update({
  id: '/pretendentes/',
  path: '/pretendentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIndexRoute = ConversasIndexRouteImport.update({
  id: '/conversas/',
  path: '/conversas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteAjudaRoute = SuporteAjudaRouteImport.update({
  id: '/suporte/ajuda',
  path: '/suporte/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteIdRoute = SuporteIdRouteImport.update({
  id: '/suporte/$id',
  path: '/suporte/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PretendentesIdRoute = PretendentesIdRouteImport.update({
  id: '/pretendentes/$id',
  path: '/pretendentes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEtapa2Route = OnboardingEtapa2RouteImport.update({
  id: '/onboarding/etapa-2',
  path: '/onboarding/etapa-2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEtapa1Route = OnboardingEtapa1RouteImport.update({
  id: '/onboarding/etapa-1',
  path: '/onboarding/etapa-1',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasMatchIdRoute = ConversasMatchIdRouteImport.update({
  id: '/conversas/$matchId',
  path: '/conversas/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificacoesRoute = AdminVerificacoesRouteImport.update({
  id: '/admin/verificacoes',
  path: '/admin/verificacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimentos': typeof DepoimentosRoute
  '/devocional': typeof DevocionalRoute
  '/interesses': typeof InteressesRoute
  '/manual': typeof ManualRoute
  '/matches': typeof MatchesRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/verificacao': typeof VerificacaoRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conversas/$matchId': typeof ConversasMatchIdRoute
  '/onboarding/etapa-1': typeof OnboardingEtapa1Route
  '/onboarding/etapa-2': typeof OnboardingEtapa2Route
  '/pretendentes/$id': typeof PretendentesIdRoute
  '/suporte/$id': typeof SuporteIdRoute
  '/suporte/ajuda': typeof SuporteAjudaRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/conversas/': typeof ConversasIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/pretendentes/': typeof PretendentesIndexRoute
  '/suporte/': typeof SuporteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimentos': typeof DepoimentosRoute
  '/devocional': typeof DevocionalRoute
  '/interesses': typeof InteressesRoute
  '/manual': typeof ManualRoute
  '/matches': typeof MatchesRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/verificacao': typeof VerificacaoRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conversas/$matchId': typeof ConversasMatchIdRoute
  '/onboarding/etapa-1': typeof OnboardingEtapa1Route
  '/onboarding/etapa-2': typeof OnboardingEtapa2Route
  '/pretendentes/$id': typeof PretendentesIdRoute
  '/suporte/$id': typeof SuporteIdRoute
  '/suporte/ajuda': typeof SuporteAjudaRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/conversas': typeof ConversasIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/pretendentes': typeof PretendentesIndexRoute
  '/suporte': typeof SuporteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloqueados': typeof BloqueadosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/depoimentos': typeof DepoimentosRoute
  '/devocional': typeof DevocionalRoute
  '/interesses': typeof InteressesRoute
  '/manual': typeof ManualRoute
  '/matches': typeof MatchesRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/verificacao': typeof VerificacaoRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conversas/$matchId': typeof ConversasMatchIdRoute
  '/onboarding/etapa-1': typeof OnboardingEtapa1Route
  '/onboarding/etapa-2': typeof OnboardingEtapa2Route
  '/pretendentes/$id': typeof PretendentesIdRoute
  '/suporte/$id': typeof SuporteIdRoute
  '/suporte/ajuda': typeof SuporteAjudaRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/conversas/': typeof ConversasIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/pretendentes/': typeof PretendentesIndexRoute
  '/suporte/': typeof SuporteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloqueados'
    | '/como-funciona'
    | '/comunidade'
    | '/dashboard'
    | '/depoimentos'
    | '/devocional'
    | '/interesses'
    | '/manual'
    | '/matches'
    | '/perfil'
    | '/sobre'
    | '/termos'
    | '/verificacao'
    | '/admin/verificacoes'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/conversas/$matchId'
    | '/onboarding/etapa-1'
    | '/onboarding/etapa-2'
    | '/pretendentes/$id'
    | '/suporte/$id'
    | '/suporte/ajuda'
    | '/admin/'
    | '/blog/'
    | '/conversas/'
    | '/noticias/'
    | '/pretendentes/'
    | '/suporte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bloqueados'
    | '/como-funciona'
    | '/comunidade'
    | '/dashboard'
    | '/depoimentos'
    | '/devocional'
    | '/interesses'
    | '/manual'
    | '/matches'
    | '/perfil'
    | '/sobre'
    | '/termos'
    | '/verificacao'
    | '/admin/verificacoes'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/conversas/$matchId'
    | '/onboarding/etapa-1'
    | '/onboarding/etapa-2'
    | '/pretendentes/$id'
    | '/suporte/$id'
    | '/suporte/ajuda'
    | '/admin'
    | '/blog'
    | '/conversas'
    | '/noticias'
    | '/pretendentes'
    | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/bloqueados'
    | '/como-funciona'
    | '/comunidade'
    | '/dashboard'
    | '/depoimentos'
    | '/devocional'
    | '/interesses'
    | '/manual'
    | '/matches'
    | '/perfil'
    | '/sobre'
    | '/termos'
    | '/verificacao'
    | '/admin/verificacoes'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/conversas/$matchId'
    | '/onboarding/etapa-1'
    | '/onboarding/etapa-2'
    | '/pretendentes/$id'
    | '/suporte/$id'
    | '/suporte/ajuda'
    | '/admin/'
    | '/blog/'
    | '/conversas/'
    | '/noticias/'
    | '/pretendentes/'
    | '/suporte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloqueadosRoute: typeof BloqueadosRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DashboardRoute: typeof DashboardRoute
  DepoimentosRoute: typeof DepoimentosRoute
  DevocionalRoute: typeof DevocionalRoute
  InteressesRoute: typeof InteressesRoute
  ManualRoute: typeof ManualRoute
  MatchesRoute: typeof MatchesRoute
  PerfilRoute: typeof PerfilRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  VerificacaoRoute: typeof VerificacaoRoute
  AdminVerificacoesRoute: typeof AdminVerificacoesRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ConversasMatchIdRoute: typeof ConversasMatchIdRoute
  OnboardingEtapa1Route: typeof OnboardingEtapa1Route
  OnboardingEtapa2Route: typeof OnboardingEtapa2Route
  PretendentesIdRoute: typeof PretendentesIdRoute
  SuporteIdRoute: typeof SuporteIdRoute
  SuporteAjudaRoute: typeof SuporteAjudaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ConversasIndexRoute: typeof ConversasIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  PretendentesIndexRoute: typeof PretendentesIndexRoute
  SuporteIndexRoute: typeof SuporteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificacao': {
      id: '/verificacao'
      path: '/verificacao'
      fullPath: '/verificacao'
      preLoaderRoute: typeof VerificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesses': {
      id: '/interesses'
      path: '/interesses'
      fullPath: '/interesses'
      preLoaderRoute: typeof InteressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devocional': {
      id: '/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof DevocionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueados': {
      id: '/bloqueados'
      path: '/bloqueados'
      fullPath: '/bloqueados'
      preLoaderRoute: typeof BloqueadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/': {
      id: '/suporte/'
      path: '/suporte'
      fullPath: '/suporte/'
      preLoaderRoute: typeof SuporteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretendentes/': {
      id: '/pretendentes/'
      path: '/pretendentes'
      fullPath: '/pretendentes/'
      preLoaderRoute: typeof PretendentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/': {
      id: '/conversas/'
      path: '/conversas'
      fullPath: '/conversas/'
      preLoaderRoute: typeof ConversasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/ajuda': {
      id: '/suporte/ajuda'
      path: '/suporte/ajuda'
      fullPath: '/suporte/ajuda'
      preLoaderRoute: typeof SuporteAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/$id': {
      id: '/suporte/$id'
      path: '/suporte/$id'
      fullPath: '/suporte/$id'
      preLoaderRoute: typeof SuporteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretendentes/$id': {
      id: '/pretendentes/$id'
      path: '/pretendentes/$id'
      fullPath: '/pretendentes/$id'
      preLoaderRoute: typeof PretendentesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/etapa-2': {
      id: '/onboarding/etapa-2'
      path: '/onboarding/etapa-2'
      fullPath: '/onboarding/etapa-2'
      preLoaderRoute: typeof OnboardingEtapa2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/etapa-1': {
      id: '/onboarding/etapa-1'
      path: '/onboarding/etapa-1'
      fullPath: '/onboarding/etapa-1'
      preLoaderRoute: typeof OnboardingEtapa1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/$matchId': {
      id: '/conversas/$matchId'
      path: '/conversas/$matchId'
      fullPath: '/conversas/$matchId'
      preLoaderRoute: typeof ConversasMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verificacoes': {
      id: '/admin/verificacoes'
      path: '/admin/verificacoes'
      fullPath: '/admin/verificacoes'
      preLoaderRoute: typeof AdminVerificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloqueadosRoute: BloqueadosRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ComunidadeRoute: ComunidadeRoute,
  DashboardRoute: DashboardRoute,
  DepoimentosRoute: DepoimentosRoute,
  DevocionalRoute: DevocionalRoute,
  InteressesRoute: InteressesRoute,
  ManualRoute: ManualRoute,
  MatchesRoute: MatchesRoute,
  PerfilRoute: PerfilRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  VerificacaoRoute: VerificacaoRoute,
  AdminVerificacoesRoute: AdminVerificacoesRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  ConversasMatchIdRoute: ConversasMatchIdRoute,
  OnboardingEtapa1Route: OnboardingEtapa1Route,
  OnboardingEtapa2Route: OnboardingEtapa2Route,
  PretendentesIdRoute: PretendentesIdRoute,
  SuporteIdRoute: SuporteIdRoute,
  SuporteAjudaRoute: SuporteAjudaRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ConversasIndexRoute: ConversasIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  PretendentesIndexRoute: PretendentesIndexRoute,
  SuporteIndexRoute: SuporteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
