// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export interface PublicSupabaseRuntimeConfig {
  supabaseUrl: string;
  publishableKey: string;
}

let runtimeConfig: PublicSupabaseRuntimeConfig | undefined;

function resolveSupabaseConfig(): PublicSupabaseRuntimeConfig | undefined {
  const supabaseUrl =
    runtimeConfig?.supabaseUrl || import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const publishableKey =
    runtimeConfig?.publishableKey ||
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  return supabaseUrl && publishableKey ? { supabaseUrl, publishableKey } : undefined;
}

export function hasSupabaseRuntimeConfig(): boolean {
  return Boolean(resolveSupabaseConfig());
}

export function configureSupabaseRuntime(config: PublicSupabaseRuntimeConfig): void {
  const url = new URL(config.supabaseUrl);
  if (url.protocol !== "https:" || config.publishableKey.trim().length < 20) {
    throw new Error("Invalid public Supabase runtime configuration");
  }

  runtimeConfig = {
    supabaseUrl: url.toString().replace(/\/$/, ""),
    publishableKey: config.publishableKey.trim(),
  };
}

function createSupabaseClient() {
  const config = resolveSupabaseConfig();

  if (!config) {
    const message =
      "Missing public Supabase runtime configuration. Connect Supabase in Lovable Cloud.";
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(config.supabaseUrl, config.publishableKey, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
